#### PI PIN-OUTS ####
STEP_PIN = 20
DIR_PIN = 21
EN_PIN = 16

LIMIT_MIN_PIN = 5
LIMIT_MAX_PIN = 6

VIB_PWM = 12
VIB_DIR = 24

VAC_PWM = 13
VAC_DIR = 25

#### STEPPER MOTOR MEASUREMENTS ####
STEPS_PER_REV = 1600
MM_PER_REV = 40.68
MM_PER_STEP = MM_PER_REV / STEPS_PER_REV

#### GANTRY / NOZZLE GEOMETRY ####
GANTRY_MIN_MM = 0.0
GANTRY_MAX_MM = 431

# Distance from gantry hard-limit reference to vacuum/nozzle center
VACUUM_CENTER_OFFSET_MM = 35.0

# Detection-based pickup correction for the current nozzle-center alignment.
# Positive values move the pickup target slightly to the right.
PICKUP_POSITION_CORRECTION_MM = 0.0

# Valid commanded nozzle-center range
OPERATIONAL_MIN_POS_MM = GANTRY_MIN_MM + VACUUM_CENTER_OFFSET_MM
OPERATIONAL_MAX_POS_MM = GANTRY_MAX_MM - VACUUM_CENTER_OFFSET_MM

#### WORK AREA LOCATIONS (NOZZLE-CENTER X POSITIONS) ####
CHANNEL_LOCATION_START = 0.0
CHANNEL_LENGTH =  149
CHANNEL_LOCATION_END = CHANNEL_LOCATION_START + CHANNEL_LENGTH
CHANNEL_CENTER = (CHANNEL_LOCATION_START + CHANNEL_LOCATION_END) / 2

CHAMBER_LOCATION_START = 156.0
CHAMBER_LENGTH = 22.0
CHAMBER_LOCATION_END = CHAMBER_LOCATION_START + CHAMBER_LENGTH
CHAMBER_CENTER = (CHAMBER_LOCATION_START + CHAMBER_LOCATION_END) / 2

TUBE_1_CENTER = 238.5
TUBE_CENTER_TO_CENTER = 30.5
TUBE_2_CENTER = TUBE_1_CENTER + TUBE_CENTER_TO_CENTER
TUBE_3_CENTER = TUBE_2_CENTER + TUBE_CENTER_TO_CENTER
TUBE_4_CENTER = TUBE_3_CENTER + TUBE_CENTER_TO_CENTER
TUBE_5_CENTER = 361.0

TUBE_SECTION_LOCATION_START = TUBE_1_CENTER
TUBE_SECTION_LOCATION_END = TUBE_5_CENTER
TUBE_SECTION_LENGTH = TUBE_SECTION_LOCATION_END - TUBE_SECTION_LOCATION_START

#### DELAYS ####
# Increased gantry speed by ~1.8x by reducing the step pulse delay.
DEFAULT_STEP_DELAY = 0.00010
# Make the initial homing sweep much faster, but keep the fine re-approach
# slower for repeatable zeroing accuracy.
HOME_STEP_DELAY = 0.00008
HOME_FINE_STEP_DELAY = 0.00024
HOME_BACKOFF_MM = 2.0
HOME_MAX_SECONDS = 15.0
# Channel-photo/setup moves should match the fast homing sweep. Transport moves
# while carrying flies still use the default profile because only the explicit
# channel-photo path opts into this timing.
CHANNEL_PHOTO_STEP_DELAY = HOME_STEP_DELAY
TIMING_FACTOR = 0.78125

VACUUM_PICK_DELAY = 0.4
VACUUM_DROP_DELAY = 0.4
CLASSIFICATION_DELAY = 1.0
VIBRATION_TIME = 2.0
