"""Core hardware and workflow constants for the Raspberry Pi drosophila rig.

The legacy motion code uses a software coordinate space where:
- 0.0 mm is the left edge of the usable nozzle travel
- the maximum commandable value is GANTRY_MAX_MM - 2 * VACUUM_CENTER_OFFSET_MM

This file preserves the original constants that existing modules expect while
also adding a few operator-workflow helpers used by the unified stitch app.
"""

#### PI PIN-OUTS ####
STEP_PIN = 20
DIR_PIN = 21
EN_PIN = 16

LIMIT_MIN_PIN = 5
LIMIT_MAX_PIN = 6
LIMIT_SWITCH_PULLUP = False

VIB_PWM = 12
VIB_DIR = 24

VAC_PWM = 13
VAC_DIR = 25

#### STEPPER MOTOR MEASUREMENTS ####
STEPS_PER_REV = 1600
MM_PER_REV = 40.68
MM_PER_STEP = MM_PER_REV / STEPS_PER_REV

#### GANTRY / NOZZLE GEOMETRY ####
GANTRY_MIN_MM = 0.0
GANTRY_MAX_MM = 431.0
VACUUM_CENTER_OFFSET_MM = 35.0

# Physical nozzle-center range when measured from the hard-limit reference.
OPERATIONAL_MIN_POS_MM = GANTRY_MIN_MM + VACUUM_CENTER_OFFSET_MM
OPERATIONAL_MAX_POS_MM = GANTRY_MAX_MM - VACUUM_CENTER_OFFSET_MM

# Software travel range used by the legacy motion stack.
SOFTWARE_POSITION_MIN_MM = 0.0
SOFTWARE_POSITION_MAX_MM = GANTRY_MAX_MM - (2.0 * VACUUM_CENTER_OFFSET_MM)

#### WORK AREA LOCATIONS (SOFTWARE X POSITIONS) ####
CHANNEL_LOCATION_START = 0.0
CHANNEL_LENGTH = 149.34
CHANNEL_LOCATION_END = CHANNEL_LOCATION_START + CHANNEL_LENGTH
CHANNEL_CENTER = (CHANNEL_LOCATION_START + CHANNEL_LOCATION_END) / 2.0

CHAMBER_LOCATION_START = 154.5
CHAMBER_LENGTH = 21.0
CHAMBER_LOCATION_END = CHAMBER_LOCATION_START + CHAMBER_LENGTH
CHAMBER_CENTER = (CHAMBER_LOCATION_START + CHAMBER_LOCATION_END) / 2.0

TUBE_1_CENTER = 238.0
TUBE_CENTER_TO_CENTER = 29.5
TUBE_2_CENTER = TUBE_1_CENTER + TUBE_CENTER_TO_CENTER
TUBE_3_CENTER = TUBE_2_CENTER + TUBE_CENTER_TO_CENTER
TUBE_4_CENTER = TUBE_3_CENTER + TUBE_CENTER_TO_CENTER
TUBE_5_CENTER = TUBE_4_CENTER + TUBE_CENTER_TO_CENTER

TUBE_SECTION_LOCATION_START = TUBE_1_CENTER
TUBE_SECTION_LOCATION_END = TUBE_5_CENTER
TUBE_SECTION_LENGTH = TUBE_SECTION_LOCATION_END - TUBE_SECTION_LOCATION_START

#### OPERATOR WORKFLOW HELPERS ####
CHANNEL_CAMERA_POSITION_MM = CHANNEL_LOCATION_END + 43.0
CHANNEL_PICKUP_OFFSET_MM = -5.0
CHAMBER_REPOSITION_OFFSET_MM = 20.0
DEFAULT_VIAL_CAPACITY = 10
DEFAULT_VIAL_TARGETS = {
    "V1": {"label": "Junk", "sex": "junk", "position_mm": TUBE_1_CENTER, "capacity": 999},
    "V2": {"label": "M1", "sex": "male", "position_mm": TUBE_2_CENTER, "capacity": DEFAULT_VIAL_CAPACITY},
    "V3": {"label": "F1", "sex": "female", "position_mm": TUBE_3_CENTER, "capacity": DEFAULT_VIAL_CAPACITY},
    "V4": {"label": "M2", "sex": "male", "position_mm": TUBE_4_CENTER, "capacity": DEFAULT_VIAL_CAPACITY},
    "V5": {"label": "F2", "sex": "female", "position_mm": TUBE_5_CENTER, "capacity": DEFAULT_VIAL_CAPACITY},
}

CHANNEL_DETECTION_PREVIEW_PATH = "../fin6/outputs/channel/last_channel_annotated.png"

#### DELAYS ####
DEFAULT_STEP_DELAY = 0.00016
HOME_STEP_DELAY = 0.00008
TIMING_FACTOR = 0.78125

VACUUM_PICK_DELAY = 0.4
VACUUM_DROP_DELAY = 0.4
CLASSIFICATION_DELAY = 1.0
VIBRATION_TIME = 2.0
