from __future__ import annotations

from enum import Enum


class StringEnum(str, Enum):
    """String enum with JSON-friendly values."""

    def __str__(self) -> str:
        return self.value


class BackendLifecycleState(StringEnum):
    POWERED_OFF = "POWERED_OFF"
    BOOTING = "BOOTING"
    STARTING_BACKEND = "STARTING_BACKEND"
    BACKEND_READY = "BACKEND_READY"
    WAITING_FOR_CLIENT = "WAITING_FOR_CLIENT"
    BACKEND_FAILED = "BACKEND_FAILED"
    SHUTTING_DOWN = "SHUTTING_DOWN"
    PROCESS_DOWN = "PROCESS_DOWN"
    SYSTEMD_RESTARTING = "SYSTEMD_RESTARTING"
    BACKEND_READY_AGAIN = "BACKEND_READY_AGAIN"
    PERSISTENT_BACKEND_FAILURE = "PERSISTENT_BACKEND_FAILURE"


class ClientControllerState(StringEnum):
    GUI_CLOSED = "GUI_CLOSED"
    GUI_STARTING = "GUI_STARTING"
    ENTRY_PAGE_ACTIVE = "ENTRY_PAGE_ACTIVE"
    CONTROL_PANEL_ACTIVE = "CONTROL_PANEL_ACTIVE"
    LOCAL_CONTROLLER_MODE = "LOCAL_CONTROLLER_MODE"
    REMOTE_CONTROLLER_MODE = "REMOTE_CONTROLLER_MODE"
    CONNECTING_TO_PI = "CONNECTING_TO_PI"
    CLIENT_CONNECTED = "CLIENT_CONNECTED"
    CLIENT_DISCONNECTED = "CLIENT_DISCONNECTED"
    RETRY_WAIT = "RETRY_WAIT"
    RECONNECT_ATTEMPT = "RECONNECT_ATTEMPT"
    CLIENT_RECONNECTED = "CLIENT_RECONNECTED"
    GUI_EXITING = "GUI_EXITING"


class OrchestratorState(StringEnum):
    SYSTEM_IDLE = "SYSTEM_IDLE"
    HOME_REQUESTED = "HOME_REQUESTED"
    MOVE_REQUESTED = "MOVE_REQUESTED"
    AUTOMATED_REQUESTED = "AUTOMATED_REQUESTED"
    ASSAY_REQUESTED = "ASSAY_REQUESTED"
    CLASSIFY_REQUESTED = "CLASSIFY_REQUESTED"
    VACUUM_ON_REQUESTED = "VACUUM_ON_REQUESTED"
    VACUUM_OFF_REQUESTED = "VACUUM_OFF_REQUESTED"
    VIBRATION_ON_REQUESTED = "VIBRATION_ON_REQUESTED"
    VIBRATION_OFF_REQUESTED = "VIBRATION_OFF_REQUESTED"
    STOP_REQUESTED = "STOP_REQUESTED"
    TASK_VALIDATING = "TASK_VALIDATING"
    COMMAND_REJECTED = "COMMAND_REJECTED"
    TASK_STARTING = "TASK_STARTING"
    ACTUATOR_APPLYING = "ACTUATOR_APPLYING"
    ACTUATOR_COMPLETE = "ACTUATOR_COMPLETE"
    TASK_STOPPING = "TASK_STOPPING"
    TASK_COMPLETE = "TASK_COMPLETE"
    TASK_ERROR = "TASK_ERROR"


class TaskState(StringEnum):
    DETECT_CHANNEL_RUNNING = "DETECT_CHANNEL_RUNNING"
    DETECT_CHANNEL_COMPLETE = "DETECT_CHANNEL_COMPLETE"
    DETECT_CHANNEL_ERROR = "DETECT_CHANNEL_ERROR"
    HOMING_RUNNING = "HOMING_RUNNING"
    HOMING_COMPLETE = "HOMING_COMPLETE"
    HOMING_STOPPED = "HOMING_STOPPED"
    HOMING_ERROR = "HOMING_ERROR"
    MOVE_RUNNING = "MOVE_RUNNING"
    MOVE_COMPLETE = "MOVE_COMPLETE"
    MOVE_LIMITED_OR_BLOCKED = "MOVE_LIMITED_OR_BLOCKED"
    MOVE_STOPPED = "MOVE_STOPPED"
    MOVE_ERROR = "MOVE_ERROR"
    ASSAY_RUNNING = "ASSAY_RUNNING"
    ASSAY_COMPLETE = "ASSAY_COMPLETE"
    ASSAY_STOPPED = "ASSAY_STOPPED"
    ASSAY_ERROR = "ASSAY_ERROR"
    CLASSIFY_RUNNING = "CLASSIFY_RUNNING"
    CLASSIFY_COMPLETE = "CLASSIFY_COMPLETE"
    CLASSIFY_STOPPED = "CLASSIFY_STOPPED"
    CLASSIFY_ERROR = "CLASSIFY_ERROR"
    AUTO_PRECHECK = "AUTO_PRECHECK"
    AUTO_CYCLE_START = "AUTO_CYCLE_START"
    AUTO_HOME_CYCLE_START = "AUTO_HOME_CYCLE_START"
    AUTO_MOVE_TO_PHOTO_POSITION = "AUTO_MOVE_TO_PHOTO_POSITION"
    AUTO_WAIT_FOR_DETECTION = "AUTO_WAIT_FOR_DETECTION"
    AUTO_NO_FLIES_REMAINING = "AUTO_NO_FLIES_REMAINING"
    AUTO_DETECTION_RETRY_WAIT = "AUTO_DETECTION_RETRY_WAIT"
    AUTO_SELECT_PICKUP = "AUTO_SELECT_PICKUP"
    AUTO_HOME_ACCURACY_RESET = "AUTO_HOME_ACCURACY_RESET"
    AUTO_MOVE_TO_PICKUP = "AUTO_MOVE_TO_PICKUP"
    AUTO_PICKUP_FLY = "AUTO_PICKUP_FLY"
    AUTO_MOVE_TO_CHAMBER = "AUTO_MOVE_TO_CHAMBER"
    AUTO_DROP_IN_CHAMBER = "AUTO_DROP_IN_CHAMBER"
    AUTO_IDENTIFICATION_WINDOW = "AUTO_IDENTIFICATION_WINDOW"
    AUTO_REPICK_FROM_CHAMBER = "AUTO_REPICK_FROM_CHAMBER"
    AUTO_SELECT_TUBE = "AUTO_SELECT_TUBE"
    AUTO_MOVE_TO_TUBE = "AUTO_MOVE_TO_TUBE"
    AUTO_DROP_IN_TUBE = "AUTO_DROP_IN_TUBE"
    AUTO_RETURN_HOME = "AUTO_RETURN_HOME"
    AUTO_ASSAY_COUNTDOWN = "AUTO_ASSAY_COUNTDOWN"
    AUTO_ASSAY_RUNNING = "AUTO_ASSAY_RUNNING"
    AUTOMATED_COMPLETE = "AUTOMATED_COMPLETE"
    AUTOMATED_STOPPED = "AUTOMATED_STOPPED"
    AUTOMATED_ERROR = "AUTOMATED_ERROR"
